# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
