# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_contactsubmission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
