# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='phone',
            field=models.IntegerField(blank=True, help_text='\n            Your phone number will not be shared in any way.\n            If you choose to enter your phone number,\n            you may recieve text messages about upcoming events.\n        ', null=True),
        ),
    ]
