# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170406_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrant',
            name='children',
        ),
        migrations.AddField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='register.Registrant'),
            preserve_default=False,
        ),
    ]
