# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170406_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='last_name',
        ),
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
