# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 22:56
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulletin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('future', 'Future'), ('past', 'Past')], max_length=20)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bulletin.Church')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
