# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 16:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
    ]
