# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 02:37
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0022_auto_20161101_2237'),
        ('display', '0002_auto_20161025_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bulletin.Church'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 2, 2, 37, 47, 796574, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accord/img/uploads/'), upload_to=''),
        ),
    ]
