# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20161101_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='slide',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('future', 'Future'), ('past', 'Past')], default='active', max_length=20),
            preserve_default=False,
        ),
    ]
