# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 19:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
            ],
            options={
                'ordering': ['sort_order', '-end_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bulletin.Campaign')),
            ],
            options={
                'ordering': ['sort_order', '-end_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('im_new', models.TextField(max_length=10000)),
                ('logo', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to='')),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.IntegerField()),
                ('foreground_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to='')),
                ('background_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to='')),
                ('podcast_url', models.URLField(blank=True)),
                ('admins', models.ManyToManyField(related_name='church', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('char', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Long Text'), ('int', 'Number'), ('bool', 'Checkbox'), ('file', 'File')], max_length=200)),
                ('required', models.BooleanField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipient', models.CharField(help_text='a comma separated list of emails', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='bulletin.Church')),
            ],
            options={
                'ordering': ['sort_order', '-end_datetime'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='bulletin.Church')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to='')),
                ('content', models.TextField(max_length=5000)),
                ('sort_order', models.IntegerField(default=0)),
                ('link_text', models.CharField(blank=True, max_length=200)),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='bulletin.Church')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin.Form')),
            ],
            options={
                'ordering': ['sort_order', '-end_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bulletin.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('gen', 'Genesis'), ('ex', 'Exodus'), ('lev', 'Leviticus'), ('num', 'Numbers'), ('deu', 'Deuteronomy'), ('joshua', 'Joshua'), ('judges', 'Judges'), ('ruth', 'Ruth'), ('1samuel', '1 Samuel'), ('2samuel', '2 Samuel'), ('1kings', '1 Kings'), ('2kings', '2 Kings'), ('1chronicles', '1 Chronicles'), ('2chronicles', '2 Chronicles'), ('ezra', 'Ezra'), ('nehimiah', 'Nehemiah'), ('esther', 'Esther'), ('job', 'Job'), ('psalms', 'Psalms'), ('proverbs', 'Proverbs'), ('ecclesiastes', 'Ecclesiastes'), ('songofsolomon', 'Song of Solomon'), ('isaiah', 'Isaiah'), ('jeremiah', 'Jeremiah'), ('lamentations', 'Lamentations'), ('ezekiel', 'Ezekiel'), ('daniel', 'Daniel'), ('hosea', 'Hosea'), ('joel', 'Joel'), ('amos', 'Amos'), ('obadiah', 'Obadiah'), ('jonah', 'Jonah'), ('micah', 'Micah'), ('nahum', 'Nahum'), ('habakkuk', 'Habakkuk'), ('zephaniah', 'Zephaniah'), ('haggai', 'Haggai'), ('zechariah', 'Zechariah'), ('malachi', 'Malachi'), ('matthew', 'Matthew'), ('mark', 'Mark'), ('luke', 'Luke'), ('john', 'John'), ('acts', 'Acts'), ('romans', 'Romans'), ('1corinthians', '1 Corinthians'), ('2corinthians', '2 Corinthians'), ('galatians', 'Galatians'), ('ephesians', 'Ephesians'), ('philippians', 'Philippians'), ('colossians', 'Colossians'), ('1thessalonians', '1 Thessalonians'), ('2thessalonians', '2 Thessalonians'), ('1timothy', '1 Timothy'), ('2timothy', '2 Timothy'), ('titus', 'Titus'), ('philemon', 'Philemon'), ('hebrews', 'Hebrews'), ('james', 'James'), ('1peter', '1 Peter'), ('2peter', '2 Peter'), ('1john', '1 John'), ('2john', '2 John'), ('3john', '3 John'), ('jude', 'Jude'), ('revelation', 'Revelation')], max_length=200)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('verse', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='starts')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='ends')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='bulletin.Church')),
            ],
            options={
                'ordering': ['sort_order', '-end_datetime'],
            },
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='bulletin.Form'),
        ),
        migrations.AddField(
            model_name='choice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='bulletin.Field'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='bulletin.Church'),
        ),
    ]
