# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, upload_to='/home3/erichigdon/public_html/static/accord/img/items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bulletin.Page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bulletin.Bulletin'),
        ),
    ]
