# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='users',
            field=models.ManyToManyField(related_name='churches', to=settings.AUTH_USER_MODEL),
        ),
    ]
