# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20161022_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bulletin',
            new_name='Church',
        ),
    ]
