# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_auto_20160914_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='title',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='slug',
            field=models.SlugField(default='bulletin', max_length=200),
            preserve_default=False,
        ),
    ]
