# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 19:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20160914_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('char', 'Text'), ('text', 'Long Text'), ('bool', 'Checkbox'), ('choice', 'Choice'), ('radio', 'Radio Choice')], max_length=200)),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='bulletin.Bulletin')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accord/img/uploads'), upload_to=''),
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='bulletin.Form'),
        ),
    ]
