# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_auto_20161001_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='template',
            field=models.TextField(default='{{ form.as_p }}', max_length=5000),
            preserve_default=False,
        ),
    ]
