# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0007_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('text', 'Long Text'), ('int', 'Number'), ('bool', 'Checkbox'), ('choice', 'Choice')], max_length=200),
        ),
    ]
