# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0008_auto_20161001_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('gen', 'Genesis'), ('ex', 'Exodus'), ('lev', 'Leviticus'), ('num', 'Numbers'), ('deu', 'Deuteronomy'), ('josh', 'Joshua'), ('judg', 'Judges'), ('ruth', 'Ruth'), ('1sam', '1 Samuel'), ('2sam', '2 Samuel'), ('1kings', '1 Kings'), ('2kings', '2 Kings'), ('1chron', '1 Chronicles'), ('2chron', '2 Chronicles'), ('ez', 'Ezra'), ('ne', 'Nehemiah'), ('es', 'Esther'), ('job', 'Job'), ('ps', 'Psalms'), ('pro', 'Proverbs'), ('ecc', 'Ecclesiastes'), ('ss', 'Song of Solomon'), ('is', 'Isaiah'), ('jer', 'Jeremiah'), ('lam', 'Lamentations'), ('ez', 'Ezekiel'), ('dan', 'Daniel'), ('hos', 'Hosea'), ('joel', 'Joel'), ('amos', 'Amos'), ('oba', 'Obadiah'), ('jonah', 'Jonah'), ('micah', 'Micah'), ('nahum', 'Nahum'), ('hab', 'Habakkuk'), ('zeph', 'Zephaniah'), ('hag', 'Haggai'), ('zech', 'Zechariah'), ('mal', 'Malachi'), ('mat', 'Matthew'), ('mk', 'Mark'), ('lk', 'Luke'), ('jn', 'John'), ('acts', 'Acts'), ('rom', 'Romans'), ('1cor', '1 Corinthians'), ('2cor', '2 Corinthians'), ('gal', 'Galatians'), ('eph', 'Ephesians'), ('philipp', 'Philippians'), ('col', 'Colossians'), ('1thes', '1 Thessalonians'), ('2thes', '2 Thessalonians'), ('1tim', '1 Timothy'), ('2tim', '2 Timothy'), ('titus', 'Titus'), ('phile', 'Philemon'), ('heb', 'Hebrews'), ('james', 'James'), ('1pet', '1 Peter'), ('2pet', '2 Peter'), ('1jn', '1 John'), ('2jn', '2 John'), ('3jn', '3 John'), ('jude', 'Jude'), ('rev', 'Revelation')], max_length=200)),
                ('chapter', models.IntegerField()),
                ('start_verse', models.IntegerField()),
                ('end_verse', models.IntegerField()),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='bulletin.Bulletin')),
            ],
        ),
        migrations.RemoveField(
            model_name='form',
            name='template',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Long Text'), ('int', 'Number'), ('bool', 'Checkbox'), ('choice', 'Choice'), ('file', 'File')], max_length=200),
        ),
    ]
