# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20161003_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='end_verse',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='start_verse',
        ),
        migrations.AddField(
            model_name='passage',
            name='verse',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
