# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20161022_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='page',
        ),
        migrations.AddField(
            model_name='item',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='bulletin.Church'),
            preserve_default=False,
        ),
    ]
