# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0011_church_im_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='form',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('char', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('text', 'Long Text'), ('int', 'Number'), ('bool', 'Checkbox'), ('file', 'File')], max_length=200),
        ),
    ]
