# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0013_formsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='church',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bulletin.Form'),
            preserve_default=False,
        ),
    ]
