# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0014_auto_20161025_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='admin',
        ),
        migrations.AddField(
            model_name='church',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
