# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 02:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0015_auto_20161025_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['sort_order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['sort_order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sort_order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['sort_order', '-pk']},
        ),
        migrations.RenameField(
            model_name='church',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='church',
            name='slug',
        ),
        migrations.AddField(
            model_name='church',
            name='address',
            field=models.CharField(default='<p>5345 Muskopf Road</p><p>Fairfield, OH 45014</p><p>513-829-6129</p>', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='logo',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
        migrations.AddField(
            model_name='church',
            name='name',
            field=models.CharField(default='Fairfield West Baptist Church', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='zip_code',
            field=models.IntegerField(default=45014, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='church',
            name='admins',
            field=models.ManyToManyField(related_name='church', to=settings.AUTH_USER_MODEL),
        ),
    ]
