# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0016_auto_20161028_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
