# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0019_auto_20161029_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='image',
            new_name='logo',
        ),
    ]
