# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 02:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0021_auto_20161029_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accord/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accord/img/uploads/'), upload_to=''),
        ),
    ]
