# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 19:56
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0022_auto_20161101_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='item',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin.Form'),
        ),
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
    ]
