# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0023_auto_20161117_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
