# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 19:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0024_item_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
    ]
