# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 01:07
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0025_auto_20170102_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='background_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
        migrations.AddField(
            model_name='church',
            name='foreground_image',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
        ),
    ]
