# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 03:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0026_auto_20170130_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='background_image',
            field=models.ImageField(blank=True, default='img/', storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='church',
            name='foreground_image',
            field=models.ImageField(blank=True, default='img', storage=django.core.files.storage.FileSystemStorage(location='/Users/erichigdon/venvs/churchapp/lib/python3.5/site-packages/django/contrib/admin/static/img/uploads/'), upload_to=''),
            preserve_default=False,
        ),
    ]
