# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 13:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0029_auto_20170131_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['sort_order', '-end_datetime']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['sort_order', '-end_datetime']},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['sort_order', '-end_datetime']},
        ),
        migrations.AddField(
            model_name='church',
            name='podcast_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_name',
            field=models.CharField(default='new submission', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='church',
            name='background_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='church',
            name='foreground_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='form',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starts'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home3/ehigdon/public_html/static/accordapp/img/uploads/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starts'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ends'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='starts'),
        ),
    ]
