# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0031_auto_20170206_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='form',
        ),
    ]
