# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0032_remove_formsubmission_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='bulletin.Church'),
            preserve_default=False,
        ),
    ]
