# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0033_formsubmission_church'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'Churches'},
        ),
    ]
